name: Update Blog Posts

on:
  schedule:
    # Runs once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-blog:
    runs-on: ubuntu-latest
    name: Fetch latest blog posts from RSS feed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://mycodingdays.com/feed.xml"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          readme_path: "./README.md"

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "Updated blog posts"
          git push
